/*PRACTICA 11*/

/*PRIMERA CONSULTA (PRODUCTO CARTESIANO)*/
/*NOMBRE SE LOS SOCIOS QUE NO TOMARON CLASES DE 'YOGA' Y QUE TIENEN ENTRE 18 Y 35 A—OS*/
SELECT DISTINCT SC.NOMBRE, C.NOMBRE_CLASE 
FROM SOCIO SC, TOMARS TS, CLASE C
WHERE SC.IDSOCIO = TS.IDSOCIO AND TS.IDCLASE = C.IDCLASE AND C.IDCLASE NOT IN (5) AND SC.EDAD BETWEEN 18 AND 35
GROUP BY SC.NOMBRE, C.NOMBRE_CLASE;

/* JOIN*/
/*CONSULTA QUE REGRESA EL NOMBRE DE LOS USUARIOS QUE HAN COMPRADO UN PRODUCTO, QUE 
SU NOMBRE EMPIECE CON 'C' Y QUE SU FECHA DE INGRESO SEA DEL A—O ACTUAL*/
SELECT DISTINCT SOCIO.NOMBRE, COMPRARS.IDPRODUCTO, PRODUCTO.NOMBRE_PRODUCTO
FROM PRODUCTO, SOCIO INNER JOIN COMPRARS ON SOCIO.IDSOCIO = COMPRARS.IDSOCIO
WHERE COMPRARS.IDPRODUCTO = PRODUCTO.IDPRODUCTO AND SOCIO.FECHA_INGRESO > '01-01-2017';

/*UNION*/
/*CONSULTA QUE REGRESA LOS SOCIOS QUE NO REALIZARON COMPRAS,
LOS SOCIOS QUE NO HAN TOMADO CLASES Y QUE TAMPOCO TIENEN UN ENTRENADOR*/
SELECT SOCIO.IDSOCIO
FROM SOCIO
WHERE SOCIO.IDSOCIO NOT IN (SELECT IDSOCIO FROM COMPRARS) AND SOCIO.IDSOCIO NOT IN (SELECT TOMARS.IDSOCIO FROM TOMARS)
UNION
SELECT SOCIO.IDSOCIO
FROM SOCIO
WHERE SOCIO.IDSOCIO NOT IN (SELECT IDSOCIO FROM SOCIOE);

/*INTERSECT*/
/*SOCIOS QUE SON MUJERES, REALIZARON UNA COMPRA Y QUE SU NOMBRE TERMINA EN 'a'*/
SELECT COMPRARS.IDSOCIO
FROM COMPRARS
INTERSECT
SELECT SOCIO.IDSOCIO
FROM SOCIO
WHERE SOCIO.SEXO = 'F' AND SOCIO.NOMBRE LIKE '%a' 
ORDER BY IDSOCIO;

/*MINUS*/
/*ID DE ENTRENADORES TALES QUE TENGAN ENTRE 25 Y 40 AÑOS Y NO DEN CLASES A SOCIOS*/
SELECT ENTRENADOR.IDEMPLEADO
FROM ENTRENADOR
WHERE ENTRENADOR.EDAD BETWEEN 25 AND 40
MINUS
SELECT SOCIOE.IDEMPLEADO
FROM SOCIOE;

/*ID DE LOS SOCIOS QUE INGRESARON AL AREA DE SAUNAS O REGADERAS*/
SELECT ACCESAR.IDSOCIO, ACCESAR.NOMBREAREA
FROM ACCESAR
WHERE ACCESAR.NOMBREAREA = 'Saunas' OR ACCESAR.NOMBREAREA = 'Regaderas' 
MINUS 
SELECT SOCIO.IDSOCIO, AREA.NOMBREAREA
FROM SOCIO, AREA;